Repository RedHatInsights/clowder, pull requests merged in 2020-10, with the labels that each got.

#86 Fix Minio secret buckets
  controllers/cloud.redhat.com/providers/objectstore/minio.go
Labels: bug

#95 Added emptydir/pvc option
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/providers/database/localdb.go
  controllers/cloud.redhat.com/providers/database/localdb_test.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis_test.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/kafka/localkafka_test.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/providers.go
Labels: enhancement

#94 Fix requeue if secret can't be found
  controllers/cloud.redhat.com/providers/objectstore/minio.go
Labels: bug

#93 Fix objects store config present when no requests made
  controllers/cloud.redhat.com/providers/objectstore/provider.go
Labels: bug

#81 RFR: Update README for unit/functional testing
  README.md
Labels: documentation
