Repository RedHatInsights/clowder, pull requests merged in 2020-11, with the labels that each got.

#77 Add kuttl test
  bundle/tests/scorecard/config.yaml
  bundle/tests/scorecard/kuttl/kuttl-test.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/00-install.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/03-delete.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/00-install.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/03-delete.yaml
  bundle/tests/scorecard/kuttl/test-local-kafka/00-assert.yaml
  bundle/tests/scorecard/kuttl/test-local-kafka/00-install.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/00-install.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/03-delete.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/skuttl_config.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/errors/errors.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  e2e-test.sh
  pr_check.Dockerfile
  pr_check.sh
  pr_check_inner.sh
  skuttl-namespace.yaml
  skuttl-perms.yaml
  skuttl.Dockerfile
  test-config.yaml
Labels: testing

#102 Creates app migration checklist
  docs/migration/checklist.md
Labels: documentation

#115 Delete old resources
  bundle/tests/scorecard/kuttl/test-rename-pod/00-install.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/02-assert.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/02-errors.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/02-pods.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/03-delete.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/proxy_client.go
Labels: enhancement

#87 Fix target namespace handling
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-target-namespace/00-install.yaml
  bundle/tests/scorecard/kuttl/test-target-namespace/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-target-namespace/02-json-asserts.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/utils/utils.go
  controllers/cloud.redhat.com/utils/utils_test.go
Labels: enhancement

#125 Fix deletion ordering
  controllers/cloud.redhat.com/clowdapp_controller.go
Labels: bug

#127 Fix env var inheritance for init containers
  controllers/cloud.redhat.com/makers/maker.go
Labels: bug
