Repository RedHatInsights/clowder, pull requests merged in 2021-04, with the labels that each got.

#270 Read bucket name from secret annotation
  bundle/tests/scorecard/kuttl/test-app-interface-s3/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-app-interface-s3/02-json-asserts.yaml
  controllers/cloud.redhat.com/providers/objectstore/appinterface.go
  controllers/cloud.redhat.com/providers/providers.go
Labels: enhancement

#288 Generation check added to ClowdApp reconciliation
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
Labels: bug, enhancement

#294 Fixed clowdapp message typo
  controllers/cloud.redhat.com/clowdapp_controller.go
Labels: bug

#285 Adds sorting to the db secret search in app-interface mode
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/02-json-asserts.yaml
  controllers/cloud.redhat.com/providers/database/appinterface.go
Labels: bug

#293 Fixed a few static check issues
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/providers/database/appinterface.go
  controllers/cloud.redhat.com/providers/database/localdb.go
  controllers/cloud.redhat.com/providers/database/none.go
  controllers/cloud.redhat.com/providers/dependencies/default.go
  controllers/cloud.redhat.com/providers/dependencies/test.go
  controllers/cloud.redhat.com/providers/deployment/default.go
  controllers/cloud.redhat.com/providers/deployment/provider.go
  controllers/cloud.redhat.com/providers/featureflags/appinterface.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/featureflags/none.go
  controllers/cloud.redhat.com/providers/inmemorydb/elasticache.go
  controllers/cloud.redhat.com/providers/inmemorydb/none.go
  controllers/cloud.redhat.com/providers/inmemorydb/provider.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/kafka/appinterface.go
  controllers/cloud.redhat.com/providers/kafka/appinterface_test.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/kafka/none.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/logging/appinterface.go
  controllers/cloud.redhat.com/providers/logging/none.go
  controllers/cloud.redhat.com/providers/logging/provider.go
  controllers/cloud.redhat.com/providers/metrics/default.go
  controllers/cloud.redhat.com/providers/metrics/provider.go
  controllers/cloud.redhat.com/providers/objectstore/appinterface.go
  controllers/cloud.redhat.com/providers/objectstore/appinterface_test.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/objectstore/minio_test.go
  controllers/cloud.redhat.com/providers/objectstore/none.go
  controllers/cloud.redhat.com/providers/objectstore/provider.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/serviceaccount/provider.go
  controllers/cloud.redhat.com/providers/servicemesh/default.go
  controllers/cloud.redhat.com/providers/servicemesh/provider.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/providers/web/default.go
  controllers/cloud.redhat.com/providers/web/provider.go
  controllers/cloud.redhat.com/suite_test.go
  controllers/cloud.redhat.com/utils/utils.go
  controllers/cloud.redhat.com/utils/utils_test.go
Labels: technical debt

#299 Update to log parser
  parse-controller-logs
Labels: enhancement, pr-non-functional-change

#297 Added basic PR flow
  docs/contributing/index.rst
  docs/contributing/prflow.rst
Labels: documentation, pr-non-functional-change

#302 Fixed docs building
  build/build_api_docs.sh
Labels: bug, pr-non-functional-change

#303 Add Kafka user and TLS spec
  controllers/cloud.redhat.com/config/schema.json
Labels: enhancement, pr-architectural-change

#273 Update kuttl tests for clowdjobs
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
Labels: bug

#306 Added generated config for kafka changes
  controllers/cloud.redhat.com/config/types.go
Labels: enhancement, pr-non-functional-change

#307 Added docs for kafka spec change
  docs/appconfig/README.md
  docs/appconfig/schema-definitions-brokerconfig-properties-authtype.md
  docs/appconfig/schema-definitions-brokerconfig-properties-cacert.md
  docs/appconfig/schema-definitions-brokerconfig.md
  docs/appconfig/schema-definitions-kafkaconfig-properties-brokerstls.md
  docs/appconfig/schema-definitions-kafkaconfig.md
  docs/appconfig/schema-definitions-kafkasaslconfig-properties-password.md
  docs/appconfig/schema-definitions-kafkasaslconfig-properties-username.md
  docs/appconfig/schema-definitions-kafkasaslconfig-properties.md
  docs/appconfig/schema-definitions-kafkasaslconfig.md
  docs/appconfig/schema.md
Labels: documentation, pr-non-functional-change

#311 Changed name of expected config file
  controllers/cloud.redhat.com/clowder_config/config.go
Labels: bug, pr-non-functional-change

#312 Updated dashboard with limits
  dashboards/clowder-dashboard.yml
Labels: enhancement, pr-non-functional-change

#310 Added profiling capabilites via config
  controllers/cloud.redhat.com/clowder_config/config.go
  main.go
  sample_config.json
Labels: enhancement, pr-functional-change

#305 Set ready status when a replica count is zero
  controllers/cloud.redhat.com/utils/utils.go
Labels: bug, pr-functional-change

#313 Fix api-docs formatting
  build/build_config_docs.sh
Labels: documentation, pr-non-functional-change

#314 Refactor strimzi topic creation
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: enhancement, pr-functional-change

#315 Fixed strimzi TLS port + no user if none requested
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/02-json-asserts.yaml
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: bug, pr-functional-change

#316 Added core docs for providers
  docs/providers/confighash.rst
  docs/providers/cronjob.rst
  docs/providers/dependencies.rst
  docs/providers/deployment.rst
  docs/providers/index.rst
  docs/providers/metrics.rst
  docs/providers/serviceaccount.rst
  docs/providers/servicemesh.rst
  docs/providers/web.rst
Labels: documentation, pr-non-functional-change

#317 Added beginnings of Antora docs
  docs/antora/antora.yml
  docs/antora/modules/ROOT/pages/contributing.adoc
  docs/antora/modules/ROOT/pages/index.adoc
  docs/antora/modules/ROOT/pages/providers/database.adoc
  docs/antora/modules/ROOT/pages/providers/index.adoc
Labels: documentation, pr-non-functional-change

#319 Multiple filtering on logs
  parse-controller-logs
Labels: enhancement, pr-non-functional-change

#318 Added new function for getting all apps in env
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
Labels: enhancement, pr-non-functional-change

#296 Add Iqe Support via Jobs
  .gitignore
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  apis/cloud.redhat.com/v1alpha1/clowdjobinvocation_types.go
  bundle/tests/scorecard/kuttl/test-iqe-jobs/00-install.yaml
  bundle/tests/scorecard/kuttl/test-iqe-jobs/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-iqe-jobs/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-iqe-jobs/03-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  config/crd/bases/cloud.redhat.com_clowdjobinvocations.yaml
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/object/object.go
  controllers/cloud.redhat.com/providers/job/impl.go
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
  controllers/cloud.redhat.com/providers/serviceaccount/impl.go
  controllers/cloud.redhat.com/suite_test.go
  controllers/cloud.redhat.com/utils/utils.go
  docs/api_reference.rst
  docs/appconfig/schema-definitions-iqeconfig-properties-imagebase.md
  docs/appconfig/schema-definitions-iqeconfig-properties.md
  docs/appconfig/schema-definitions-iqeconfig.md
  docs/appconfig/schema-definitions-testingconfig-properties-configaccess.md
  docs/appconfig/schema-definitions-testingconfig-properties-k8saccesslevel.md
  docs/appconfig/schema-definitions-testingconfig-properties.md
  docs/appconfig/schema-definitions-testingconfig.md
  docs/usage/jobs.rst
Labels: enhancement, pr-architectural-change

#301 Added kafka managed mode
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-kafka-managed/00-install.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/03-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/providers/kafka/managed.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
  docs/api_reference.rst
Labels: enhancement, pr-functional-change

#290 Removed consumerGroup
  controllers/cloud.redhat.com/config/schema.json
  controllers/cloud.redhat.com/config/types.go
  docs/appconfig/schema-definitions-topicconfig.md
  docs/appconfig/schema.md
Labels: on hold, pr-architectural-change, requires client sync

#321 Moved API docs generation to adoc
  build/build_api_docs.sh
  docs/antora/modules/ROOT/pages/api_reference.adoc
  docs/antora/modules/ROOT/pages/index.adoc
Labels: documentation, pr-non-functional-change
