Repository RedHatInsights/clowder, pull requests merged in 2021-02, with the labels that each got.

#205 Reduce complexity of reconcile function
  controllers/cloud.redhat.com/proxy_client.go
Labels: technical debt

#210 Allow any real provider to be omitted
  controllers/cloud.redhat.com/providers/database/provider.go
  controllers/cloud.redhat.com/providers/featureflags/provider.go
  controllers/cloud.redhat.com/providers/inmemorydb/provider.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
  controllers/cloud.redhat.com/providers/logging/provider.go
  controllers/cloud.redhat.com/providers/objectstore/provider.go
Labels: enhancement

#208 Add "how to use" guide
  docs/developer-guide.md
  docs/examples/clowdapp.yml
  docs/examples/clowdenv.yml
  docs/usage/app-workflow.rst
  docs/usage/getting-started.rst
Labels: documentation

#211 Added provider reference docs
  .gitignore
  docs/Makefile
  docs/clowder-design.rst
  docs/conf.py
  docs/images/config-fonts.svg
  docs/index.rst
  docs/migration/README.rst
  docs/providers/database.rst
  docs/providers/featureflags.rst
  docs/providers/index.rst
  docs/providers/inmemorydb.rst
  docs/providers/kafka.rst
  docs/providers/logging.rst
  docs/providers/objectstore.rst
Labels: documentation

#207 Fix strimzi complexity
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: technical debt
