Repository RedHatInsights/clowder, pull requests merged in 2021-07, with the labels that each got.

#374 Update Redis and Unleash to Use Quay Images
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
Labels: bug, pr-non-functional-change

#383 Updated strimzi version
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#384 Allow empty connect cluster name
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  docs/antora/modules/ROOT/pages/api_reference.adoc
  docs/antora/modules/ROOT/pages/developer-guide.adoc
Labels: enhancement, pr-architectural-change

#394 Working annotation db implementation
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/02-json-asserts.yaml
  controllers/cloud.redhat.com/clowder_config/config.go
  controllers/cloud.redhat.com/providers/database/appinterface.go
  docs/antora/modules/providers/pages/database.adoc
Labels: enhancement, pr-functional-change

#401 Fix node port usage
  controllers/cloud.redhat.com/utils/utils.go
Labels: bug, pr-functional-change

#408 Use a configurable KUBECTL_CMD in kube_setup.sh
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#405 Fixed 'test' target in the Makefile
  Makefile
Labels: bug, pr-non-functional-change

#403 Kuttl test improvements
  bundle/tests/scorecard/kuttl/kuttl-test.yaml
Labels: enhancement, pr-non-functional-change
