Repository RedHatInsights/clowder, pull requests merged in 2021-08, with the labels that each got.

#412 Fix app sharing with annotations
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/01-pods.yaml
  controllers/cloud.redhat.com/providers/database/appinterface.go
Labels: bug, pr-functional-change

#413 Dash update
  dashboards/clowder-dashboard.yml
Labels: bug, pr-non-functional-change

#411 Added disabled flags
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-disabled-delete/00-install.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/02-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/03-errors.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/03-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled-delete/04-delete.yaml
  bundle/tests/scorecard/kuttl/test-disabled/00-install.yaml
  bundle/tests/scorecard/kuttl/test-disabled/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-disabled/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled/02-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled/03-errors.yaml
  bundle/tests/scorecard/kuttl/test-disabled/03-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled/04-assert.yaml
  bundle/tests/scorecard/kuttl/test-disabled/04-pods.yaml
  bundle/tests/scorecard/kuttl/test-disabled/05-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: enhancement, pr-architectural-change

#415 Add Postgress port to Istio exclude rule
  bundle/tests/scorecard/kuttl/test-service-mesh/01-assert.yaml
  controllers/cloud.redhat.com/providers/servicemesh/default.go
Labels: enhancement, pr-non-functional-change

#407 upgrading strimzi client
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  go.mod
  go.sum
Labels: bug, pr-architectural-change

#418 Added PW for elasticache
  controllers/cloud.redhat.com/providers/inmemorydb/elasticache.go
Labels: enhancement, pr-functional-change

#410 Add pvc check to switch to recreate strategy
  bundle/tests/scorecard/kuttl/test-basic-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-recreate-strategy/00-install.yaml
  bundle/tests/scorecard/kuttl/test-recreate-strategy/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-recreate-strategy/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-recreate-strategy/02-delete.yaml
  controllers/cloud.redhat.com/providers/deployment/impl.go
  docs/antora/modules/providers/pages/deployment.adoc
Labels: enhancement, pr-functional-change

#422 Add 'deployment metadata' to cdappconfig
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/config/types.go
  controllers/cloud.redhat.com/suite_test.go
Labels: enhancement, pr-architectural-change

#428 Fix clowd conditions for env
  controllers/cloud.redhat.com/clowdenvironment_controller.go
Labels: bug, pr-functional-change
