Repository RedHatInsights/clowder, pull requests merged in 2021-12, with the labels that each got.

#526 [RHCLOUD-17103] Switched to UBI8 minimal
  Dockerfile
  build/Dockerfile-local
Labels: enhancement, pr-non-functional-change

#518 [RHCLOUD-16682] Cloudwatch logging
  config/manager/manager.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowderconfig/config.go
  deploy-mutate.yml
  deploy.yml
  go.mod
  go.sum
  main.go
Labels: enhancement, pr-functional-change

#522 [RHCLOUD-17087] Migrate to resource cache lib
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/providers/autoscaler/default.go
  controllers/cloud.redhat.com/providers/confighash/default.go
  controllers/cloud.redhat.com/providers/cronjob/provider.go
  controllers/cloud.redhat.com/providers/database/localdb.go
  controllers/cloud.redhat.com/providers/database/shareddb.go
  controllers/cloud.redhat.com/providers/deployment/provider.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/iqe/impl.go
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/metrics/impl.go
  controllers/cloud.redhat.com/providers/metrics/operator.go
  controllers/cloud.redhat.com/providers/metrics/provider.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/pullsecrets/default.go
  controllers/cloud.redhat.com/providers/pullsecrets/provider.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
  controllers/cloud.redhat.com/providers/serviceaccount/impl.go
  controllers/cloud.redhat.com/providers/serviceaccount/provider.go
  controllers/cloud.redhat.com/providers/web/impl.go
  controllers/cloud.redhat.com/providers/web/local.go
  controllers/cloud.redhat.com/providers/web/provider.go
  controllers/cloud.redhat.com/run.go
  controllers/cloud.redhat.com/suite_test.go
  docs/antora/modules/ROOT/pages/contributing.adoc
Labels: enhancement, pr-functional-change

#535 Added per_provider_metrics option in template
  config/deployment-template/clowder_config.yaml
  deploy-mutate.yml
  deploy.yml
  template.yml
Labels: enhancement, pr-non-functional-change

#538 Update concurrent
  controllers/cloud.redhat.com/clowdapp_controller.go
Labels: enhancement, pr-functional-change

#454 [RHCLOUD-16216] Update k8s batch/v1beta1 to batch/v1
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  bundle/tests/scorecard/kuttl/test-clowder-jobs/01-assert.yaml
  controllers/cloud.redhat.com/providers/confighash/default.go
  controllers/cloud.redhat.com/providers/cronjob/impl.go
  controllers/cloud.redhat.com/providers/cronjob/provider.go
  controllers/cloud.redhat.com/providers/sidecar/default.go
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: pr-functional-change, uprev

#536 [RHCLOUD-16525] Added pull policy flag
  Makefile
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  bundle/tests/scorecard/kuttl/test-pull-policy/00-install.yaml
  bundle/tests/scorecard/kuttl/test-pull-policy/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-pull-policy/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-pull-policy/02-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/providers/cronjob/impl.go
  controllers/cloud.redhat.com/providers/deployment/impl.go
  controllers/cloud.redhat.com/providers/job/impl.go
  deploy-mutate.yml
  deploy.yml
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: enhancement, pr-architectural-change

#545 Optimize the pullsecret function
  controllers/cloud.redhat.com/providers/pullsecrets/default.go
Labels: enhancement, pr-functional-change

#547 Fix trigger reconcile
  controllers/cloud.redhat.com/predicates.go
Labels: bug, pr-functional-change

#548 [RHCLOUD-17349] Minor perf improvments
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/providers/dependencies/impl.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: technical debt, pr-functional-change

#550 [RHCLOUD-17355] Updated k8s libs
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  controllers/cloud.redhat.com/providers/autoscaler/default.go
  controllers/cloud.redhat.com/providers/autoscaler/impl.go
  controllers/cloud.redhat.com/run.go
  controllers/cloud.redhat.com/suite_test.go
  docs/antora/modules/ROOT/pages/api_reference.adoc
  go.mod
  go.sum
Labels: technical debt, pr-functional-change

#551 [RHCLOUD-17365] Fix bug in env ready
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
Labels: bug, pr-functional-change

#552 [RHCLOUD-17377] Fix error handling
  controllers/cloud.redhat.com/errors/errors.go
Labels: bug, pr-functional-change

#553 [RHCLOUD-17381] Fix cyndi with shared DB mode
  apis/cloud.redhat.com/v1alpha1/clowdapp_webhook.go
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
Labels: bug, pr-functional-change
