Repository RedHatInsights/clowder, pull requests merged in 2021-05, with the labels that each got.

#322 Setup iqe jobs to only use a single service account
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-iqe-jobs/01-assert.yaml
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
  controllers/cloud.redhat.com/providers/serviceaccount/provider.go
Labels: pr-functional-change

#327 Upped time out and reduced parallel
  bundle/tests/scorecard/kuttl/kuttl-test.yaml
  controllers/cloud.redhat.com/suite_test.go
Labels: bug, pr-non-functional-change

#304 Convert pullSecrets to namespacedNames
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-basic-app/00-install.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-ff-local/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-k8s-access/00-install.yaml
  bundle/tests/scorecard/kuttl/test-k8s-access/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-k8s-access/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/01-assert.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/providers/metrics/provider.go
  controllers/cloud.redhat.com/providers/pullsecrets/default.go
  controllers/cloud.redhat.com/providers/pullsecrets/provider.go
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
  controllers/cloud.redhat.com/providers/serviceaccount/impl.go
Labels: enhancement, pr-architectural-change

#325 Add support for postgresql 13 in local db provider
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  controllers/cloud.redhat.com/providers/database/provider.go
Labels: enhancement, pr-functional-change

#336 Fix object store PVC
  controllers/cloud.redhat.com/providers/objectstore/minio.go
Labels: bug, pr-functional-change

#335 Install cyndi-operator in kube_setup.sh
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#338 Removed old make component
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/providers.go
Labels: enhancement, pr-functional-change

#334 More descriptive error messages for elasticache provider
  controllers/cloud.redhat.com/providers/inmemorydb/elasticache.go
Labels: enhancement, pr-functional-change

#328 Move IQE job logic out of invocation controller
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/providers/iqe/impl.go
Labels: pr-functional-change, technical debt

#287 Add prometheus service monitor
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  build/kube_setup.sh
  build/pr_check_inner.sh
  bundle/tests/scorecard/kuttl/test-app-interface-s3/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-basic-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-elasticache/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-metrics-app-interface/00-install.yaml
  bundle/tests/scorecard/kuttl/test-metrics-app-interface/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-metrics-app-interface/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-metrics-app-interface/02-delete.yaml
  bundle/tests/scorecard/kuttl/test-metrics-operator/00-install.yaml
  bundle/tests/scorecard/kuttl/test-metrics-operator/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-metrics-operator/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-metrics-operator/02-delete.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-multi-db/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-service-mesh/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-web-services/02-json-asserts.yaml
  clowder-config.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  config/rbac/auth_proxy_reader.yaml
  config/rbac/clowder_prometheus.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowder_config/config.go
  controllers/cloud.redhat.com/providers/metrics/appinterface.go
  controllers/cloud.redhat.com/providers/metrics/default.go
  controllers/cloud.redhat.com/providers/metrics/impl.go
  controllers/cloud.redhat.com/providers/metrics/none.go
  controllers/cloud.redhat.com/providers/metrics/operator.go
  controllers/cloud.redhat.com/providers/metrics/provider.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/run.go
  docs/api_reference.rst
  go.mod
  go.sum
Labels: enhancement, pr-architectural-change

#337 Upgrade golang version
  Dockerfile
Labels: enhancement, pr-architectural-change

#339 Enable node port
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-node-port/00-install.yaml
  bundle/tests/scorecard/kuttl/test-node-port/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-node-port/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-node-port/02-assert.yaml
  bundle/tests/scorecard/kuttl/test-node-port/02-pods.yaml
  bundle/tests/scorecard/kuttl/test-node-port/03-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis_test.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/kafka/localkafka_test.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/providers/web/impl.go
  controllers/cloud.redhat.com/utils/utils.go
  controllers/cloud.redhat.com/utils/utils_test.go
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: enhancement, pr-architectural-change

#340 Default kafka cluster name to env name
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/02-json-asserts.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  controllers/cloud.redhat.com/providers/kafka/provider.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: enhancement, pr-functional-change
