Repository RedHatInsights/clowder, pull requests merged in 2021-03, with the labels that each got.

#244 Simplify test function
  controllers/cloud.redhat.com/suite_test.go
Labels: enhancement, testing

#255 Fixed own app endpoints in the case an app has no deps
  bundle/tests/scorecard/kuttl/test-basic-app/02-json-asserts.yaml
  controllers/cloud.redhat.com/makers/maker.go
  controllers/cloud.redhat.com/makers/makers_test.go
Labels: bug

#245 add `minikube config` settings to readme
  README.md
Labels: documentation

#257 Add docs building to PR check
  pr_check.sh
Labels: documentation

#240 adding isReady() func
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
Labels: enhancement

#258 Add SSL Mode
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-multi-db/02-json-asserts.yaml
  controllers/cloud.redhat.com/config/schema.json
  controllers/cloud.redhat.com/config/types.go
  controllers/cloud.redhat.com/providers/database/appinterface.go
  controllers/cloud.redhat.com/providers/database/localdb.go
  docs/api_reference.rst
  docs/appconfig/schema-definitions-databaseconfig-properties-sslmode.md
  docs/appconfig/schema-definitions-databaseconfig.md
  docs/appconfig/schema.md
Labels: enhancement, requires client sync

#260 Add profiling capability
  main.go
Labels: enhancement

#261 RFR: Create db secrets needed for cyndi operator, remove local kafka cyndi support
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  bundle/tests/scorecard/kuttl/test-cyndi-local-kafka/00-install.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-local-kafka/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-local-kafka/01-install.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-local-kafka/02-delete.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/01-install.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/03-delete.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: enhancement

#265 Changed labels
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  bundle/tests/scorecard/kuttl/test-basic-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-clowder-jobs/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-elasticache/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-deprecated-spec/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-local-kafka/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-minio-app/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-rename-pod/02-assert.yaml
  bundle/tests/scorecard/kuttl/test-web-services/01-assert.yaml
  controllers/cloud.redhat.com/makers/makers_test.go
  controllers/cloud.redhat.com/providers/database/localdb_test.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/suite_test.go
  controllers/cloud.redhat.com/utils/utils_test.go
Labels: enhancement

#269 Add bucket region to config
  bundle/tests/scorecard/kuttl/test-app-interface-s3/00-install.yaml
  bundle/tests/scorecard/kuttl/test-app-interface-s3/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-app-interface-s3/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-app-interface-s3/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-app-interface-s3/03-delete.yaml
  controllers/cloud.redhat.com/config/schema.json
  controllers/cloud.redhat.com/config/types.go
  controllers/cloud.redhat.com/providers/objectstore/appinterface.go
  docs/api_reference.rst
  docs/appconfig/schema-definitions-objectstorebucket-properties-region.md
  docs/appconfig/schema-definitions-objectstorebucket.md
  docs/appconfig/schema.md
Labels: enhancement, requires client sync

#278 Change 25 to 25% for rollouts
  controllers/cloud.redhat.com/makers/maker.go
Labels: bug

#281 Refactor updates for tech debt
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/providers/confighash/default.go
  controllers/cloud.redhat.com/providers/cronjob/default.go
  controllers/cloud.redhat.com/providers/cronjob/impl.go
  controllers/cloud.redhat.com/providers/dependencies/default.go
  controllers/cloud.redhat.com/providers/dependencies/impl.go
  controllers/cloud.redhat.com/providers/deployment/default.go
  controllers/cloud.redhat.com/providers/deployment/impl.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/metrics/default.go
  controllers/cloud.redhat.com/providers/metrics/impl.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/serviceaccount/always.go
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
  controllers/cloud.redhat.com/providers/serviceaccount/impl.go
  controllers/cloud.redhat.com/providers/serviceaccount/provider.go
  controllers/cloud.redhat.com/providers/servicemesh/default.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/providers/web/default.go
  controllers/cloud.redhat.com/providers/web/impl.go
Labels: enhancement
