Repository RedHatInsights/clowder, pull requests merged in 2021-09, with the labels that each got.

#434 Fixed namespace delete in test
  bundle/tests/scorecard/kuttl/test-ff-app-interface/03-delete.yaml
Labels: bug, pr-non-functional-change

#433 Attempt to fix strimzi tests with cluster name uniqueness
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/01-install.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-deprecated-spec/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-deprecated-spec/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-multiple-app-endpoints/01-pods.yaml
Labels: enhancement, pr-non-functional-change

#190 Removed deprecated Pods support
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  bundle/tests/scorecard/kuttl/test-app-interface-s3/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-cyndi-strimzi/01-install.yaml
  bundle/tests/scorecard/kuttl/test-elasticache/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-multi-db/01-pods.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/providers/dependencies/impl.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: enhancement

#436 Decrease concurrent kuttl tests for stability increase
  bundle/tests/scorecard/kuttl/kuttl-test.yaml
Labels: pr-non-functional-change

#437 Remove yq
  .gitignore
  build/fix_namespace.py
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#441 Fix PVC deployment strategy
  controllers/cloud.redhat.com/providers/utils/utils.go
Labels: bug, pr-functional-change

#438 Update strimzi
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  build/kube_setup.sh
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-ephemeral/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-pvc/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-deprecated-spec/01-assert.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  config/crd/static/kafkaconnects.kafka.strimzi.io.yaml
  config/crd/static/kafkas.kafka.strimzi.io.yaml
  config/crd/static/kafkatopics.kafka.strimzi.io.yaml
  config/crd/static/kafkausers.kafka.strimzi.io.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/providers/kafka/appinterface.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/run.go
  controllers/cloud.redhat.com/status.go
  controllers/cloud.redhat.com/suite_test.go
  go.mod
  go.sum
Labels: enhancement, pr-non-functional-change

#432 Add deployment metadata to cdappconfig
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/config/types.go
  controllers/cloud.redhat.com/suite_test.go
Labels: enhancement, pr-architectural-change

#443 Update dependent operator versions in kube_setup.sh
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#444 Downloading fix_namespaces.py if missing
  build/kube_setup.sh
Labels: bug, pr-non-functional-change

#449 Fix test with missing pod assert
  bundle/tests/scorecard/kuttl/test-multi-app-interface-db/01-assert.yaml
Labels: testing, pr-non-functional-change

#448 Requeue properly if env not ready
  controllers/cloud.redhat.com/clowdapp_controller.go
Labels: enhancement, pr-functional-change

#446 Cyndi support for strimzi mode with app-interface db
  controllers/cloud.redhat.com/config/config.go
  controllers/cloud.redhat.com/providers/database/appinterface.go
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
  controllers/cloud.redhat.com/providers/objectstore/appinterface.go
  controllers/cloud.redhat.com/providers/providers.go
Labels: enhancement, pr-functional-change

#456 kuttle testsfor eph gateway
  bundle/tests/scorecard/kuttl/test-ephemeral-gateway/00-install.yaml
  bundle/tests/scorecard/kuttl/test-ephemeral-gateway/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-ephemeral-gateway/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-ephemeral-gateway/02-json-assert.yaml
  bundle/tests/scorecard/kuttl/test-ephemeral-gateway/03-delete.yaml
Labels: testing, pr-non-functional-change

#458 Remove bad env secret from test
  bundle/tests/scorecard/kuttl/test-validator/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-validator/02-pods.yaml
Labels: bug, testing, pr-non-functional-change
