Repository RedHatInsights/clowder, pull requests merged in 2021-06, with the labels that each got.

#343 Added strimzi network policy
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/01-assert.yaml
  controllers/cloud.redhat.com/providers/deployment/impl.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
Labels: enhancement, pr-functional-change

#353 Added option for simple/complex topic names
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-basic/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-deprecated-spec/01-assert.yaml
  controllers/cloud.redhat.com/clowder_config/config.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/suite_test.go
Labels: bug, pr-functional-change

#359 Added new test to cover cache invalid access mechanism
  controllers/cloud.redhat.com/suite_test.go
Labels: pr-non-functional-change, testing

#365 Bump release link on README.adoc
  README.adoc
Labels: documentation, pr-non-functional-change

#368 add Mac checks to kube_setup
  build/kube_setup.sh
Labels: enhancement, pr-non-functional-change

#351 Convert IQE CJI to use iqe-core image's entrypoint command
  apis/cloud.redhat.com/v1alpha1/clowdjobinvocation_types.go
  bundle/tests/scorecard/kuttl/test-iqe-jobs/01-assert.yaml
  controllers/cloud.redhat.com/providers/iqe/impl.go
Labels: enhancement, pr-architectural-change

#377 Added new dependencies diagram
  docs/antora/modules/ROOT/images/clowder-deps.svg
Labels: documentation, pr-non-functional-change

#381 Fixed test
  bundle/tests/scorecard/kuttl/test-iqe-jobs/01-assert.yaml
Labels: bug, pr-non-functional-change, testing
