Repository RedHatInsights/clowder, pull requests merged in 2021-11, with the labels that each got.

#487 Add activeDeadlineSeconds to ClowdJob
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/zz_generated.deepcopy.go
  bundle/tests/scorecard/kuttl/test-clowder-jobs/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-clowder-jobs/01-pods.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  controllers/cloud.redhat.com/providers/cronjob/impl.go
  controllers/cloud.redhat.com/providers/job/impl.go
  deploy-mutate.yml
  deploy.yml
  docs/antora/modules/ROOT/pages/api_reference.adoc
  docs/appconfig/schema-definitions-appmetadata-properties-envname.md
  docs/appconfig/schema-definitions-appmetadata-properties-name.md
  docs/appconfig/schema-definitions-appmetadata.md
  docs/appconfig/schema.md
Labels: enhancement, pr-architectural-change

#488 Remove Partial Reconciliation
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/providers/web/local.go
  controllers/cloud.redhat.com/status.go
Labels: enhancement, pr-functional-change

#490 Fix DB images
  bundle/tests/scorecard/kuttl/test-cyndi-local-db/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-multi-db-shared/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-multi-db/01-assert.yaml
  controllers/cloud.redhat.com/providers/database/provider.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
Labels: enhancement, pr-functional-change

#494 Add option to disable Keda resource listing
  clowder-config.yaml
  controllers/cloud.redhat.com/clowder_config/config.go
  controllers/cloud.redhat.com/providers/resource_cache.go
Labels: bug, pr-functional-change

#497 Fix requeue timings
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
Labels: enhancement, pr-functional-change

#491 Fix bug in service account
  controllers/cloud.redhat.com/providers/serviceaccount/default.go
Labels: bug, pr-functional-change

#496 Fixed Keda tests
  bundle/tests/scorecard/kuttl/test-autoscaler/02-delete.yaml
  bundle/tests/scorecard/kuttl/test-kafka-app-autoscale/02-json-asserts.yaml
Labels: testing, pr-non-functional-change

#505 Fixed missing crds
  config/crd/static/prometheus.prometheus.yaml
  config/crd/static/prometheus.servicemonitors.yaml
Labels: testing, pr-non-functional-change

#502 Enhance backoffs for remaining controllers
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
Labels: enhancement, pr-functional-change

#509 Fixed duplicate acg_config env var
  bundle/tests/scorecard/kuttl/test-basic-app/01-assert.yaml
  controllers/cloud.redhat.com/providers/deployment/impl.go
Labels: bug, pr-functional-change

#513 Added speed up for bin
  build/pr_check_inner.sh
Labels: enhancement, pr-non-functional-change

#510 Fix autoscalar replicas
  controllers/cloud.redhat.com/providers/deployment/impl.go
Labels: bug, pr-functional-change

#503 Better write now support
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/providers/web/local.go
  controllers/cloud.redhat.com/providers/web/provider.go
Labels: enhancement, pr-functional-change

#520 Fixed some more TODOs
  apis/cloud.redhat.com/v1alpha1/clowdapp_webhook.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/errors/errors.go
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
  controllers/cloud.redhat.com/providers/objectstore/minio_test.go
  controllers/cloud.redhat.com/providers/utils/utils.go
Labels: enhancement, technical debt, pr-functional-change

#521 Fixed a number of standards issues
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowderconfig/config.go
  controllers/cloud.redhat.com/clowderconfig/config_test.go
  controllers/cloud.redhat.com/clowderconfig/test_config.json
  controllers/cloud.redhat.com/clowdjobinvocation_controller.go
  controllers/cloud.redhat.com/object/object.go
  controllers/cloud.redhat.com/pod_mutator.go
  controllers/cloud.redhat.com/providers/autoscaler/default.go
  controllers/cloud.redhat.com/providers/cronjob/provider.go
  controllers/cloud.redhat.com/providers/database/shareddb.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  controllers/cloud.redhat.com/providers/metrics/appinterface.go
  controllers/cloud.redhat.com/providers/metrics/operator.go
  controllers/cloud.redhat.com/providers/resource_cache.go
  controllers/cloud.redhat.com/providers/web/impl.go
  controllers/cloud.redhat.com/providers/web/local.go
  controllers/cloud.redhat.com/run.go
  controllers/cloud.redhat.com/status.go
  main.go
Labels: enhancement, technical debt, pr-functional-change
