Repository RedHatInsights/clowder, pull requests merged in 2022-05, with the labels that each got.

#608 [RHCLOUD-19214] Fix ns we expect to find cert-manager-webhook in
  build/kube_setup.sh
Labels: bug, pr-non-functional-change

#597 [RHCLOUD-18319] Add localdb resource requirements T Shirt sizing
  .gitignore
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
  build/kube_setup.sh
  build_deploy.sh
  bundle/tests/scorecard/config.yaml
  bundle/tests/scorecard/kuttl/test-autoscaler/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-autoscaler/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-db-resource-tee/00-install.yaml
  bundle/tests/scorecard/kuttl/test-db-resource-tee/01-assert.yaml
  bundle/tests/scorecard/kuttl/test-db-resource-tee/01-pods.yaml
  bundle/tests/scorecard/kuttl/test-db-resource-tee/02-delete.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/03-delete.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/04-json-asserts.yaml
  clowder-config.yaml
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  config/crd/bases/cloud.redhat.com_clowdenvironments.yaml
  config/deployment-template/clowder_config.yaml
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdapp_controller_test.go
  controllers/cloud.redhat.com/clowderconfig/config.go
  controllers/cloud.redhat.com/metrics.go
  controllers/cloud.redhat.com/pod_mutator.go
  controllers/cloud.redhat.com/providers/database/localdb.go
  controllers/cloud.redhat.com/providers/database/localdb_test.go
  controllers/cloud.redhat.com/providers/database/shareddb.go
  controllers/cloud.redhat.com/providers/deployment/impl.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/kafka/managed.go
  controllers/cloud.redhat.com/providers/providers.go
  controllers/cloud.redhat.com/providers/sizing/sizing.go
  controllers/cloud.redhat.com/providers/sizing/sizing_test.go
  controllers/cloud.redhat.com/providers/sizing/sizingconfig/sizingconfig.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/providers/web/impl.go
  controllers/cloud.redhat.com/providers/web/local.go
  controllers/cloud.redhat.com/utils/utils.go
  deploy-mutate.yml
  deploy.yml
  docs/antora/modules/ROOT/pages/api_reference.adoc
  docs/appconfig/README.md
  pr_check.sh
  sample_config.json
  template.yml
Labels: enhancement, pr-architectural-change

#613 [RHCLOUD-18895] Added FAQ entry for DB migrate
  docs/antora/modules/ROOT/pages/faq.adoc
Labels: documentation, enhancement

#611 [RHCLOUD-19289] Add new spec item for external HPA
  apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  deploy-mutate.yml
  deploy.yml
  docs/antora/modules/ROOT/pages/api_reference.adoc
Labels: enhancement, pr-architectural-change

#614 [RHCLOUD-19333] Updated to golang 1.17
  .github/workflows/package.yml
  Dockerfile.base
  Makefile
  build/pr_check_inner.sh
  config/crd/bases/cloud.redhat.com_clowdapps.yaml
  controllers/cloud.redhat.com/providers/deployment/impl.go
  controllers/cloud.redhat.com/providers/featureflags/localfeatureflags.go
  controllers/cloud.redhat.com/providers/inmemorydb/redis.go
  controllers/cloud.redhat.com/providers/kafka/localkafka.go
  controllers/cloud.redhat.com/providers/objectstore/minio.go
  controllers/cloud.redhat.com/providers/utils/utils.go
  controllers/cloud.redhat.com/providers/web/impl.go
  controllers/cloud.redhat.com/utils/utils.go
  deploy-mutate.yml
  deploy.yml
  docs/antora/modules/ROOT/pages/api_reference.adoc
  docs/appconfig/README.md
  go.mod
  go.sum
  pr_check.sh
Labels: enhancement, pr-functional-change

#615 [RHCLOUD-19317] Add SASL auth metadata
  bundle/tests/scorecard/kuttl/test-kafka-managed/02-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-managed/04-json-asserts.yaml
  bundle/tests/scorecard/kuttl/test-kafka-strimzi-topic-auth/02-json-asserts.yaml
  controllers/cloud.redhat.com/config/schema.json
  controllers/cloud.redhat.com/config/types.go
  controllers/cloud.redhat.com/providers/kafka/managed.go
  controllers/cloud.redhat.com/providers/kafka/strimzi.go
  docs/appconfig/schema-definitions-kafkasaslconfig-properties-saslmechanism.md
  docs/appconfig/schema-definitions-kafkasaslconfig-properties-securityprotocol.md
  docs/appconfig/schema-definitions-kafkasaslconfig.md
  docs/appconfig/schema.md
Labels: enhancement, pr-architectural-change
