Repository RedHatInsights/clowder, pull requests merged in 2022-09, with the labels that each got.

#687 [RHCLOUD-15674] Change missing dependency errors to be more explicit
  controllers/cloud.redhat.com/errors/errors.go
  controllers/cloud.redhat.com/providers/database/appinterface.go
  controllers/cloud.redhat.com/providers/dependencies/impl.go
  controllers/cloud.redhat.com/providers/inmemorydb/elasticache.go
  controllers/cloud.redhat.com/providers/kafka/appinterface.go
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
Labels: enhancement, pr-functional-change

#700 RHCLOUD-21170: Add cyndi ConfigMap when kafka provider is managed-ephem
  controllers/cloud.redhat.com/providers/kafka/cyndi.go
  controllers/cloud.redhat.com/providers/kafka/managed-ephem.go
  controllers/cloud.redhat.com/providers/kafka/provider.go
Labels: bug, pr-functional-change

#690 Reduce complexity of Clowder methods
  controllers/cloud.redhat.com/clowdapp_controller.go
  controllers/cloud.redhat.com/clowdapp_reconciliation.go
  controllers/cloud.redhat.com/clowdenvironment_controller.go
  controllers/cloud.redhat.com/clowdenvironment_reconciliation.go
  controllers/cloud.redhat.com/providers/deployment/impl.go
Labels: technical debt, pr-functional-change
