Repository RedHatInsights/clowder, pull requests merged in 2024-01, with the labels that each got.

#925 [RHCLOUD-30525] - fix: Caddy TLS proxy disable auto_https
  controllers/cloud.redhat.com/providers/web/caddy_reverse_proxy.go
Labels: bug, pr-functional-change

#926 [RHCLOUD-30524] - Fix test flakiness
  tests/kuttl/test-ff-local/01-assert.yaml
Labels: testing, pr-non-functional-change

#856 Bumping Prometheus Operator version
  build/kube_setup.sh
  controllers/cloud.redhat.com/providers/metrics/operator.go
  go.mod
  go.sum
  tests/kuttl/test-metrics-operator/01-assert.yaml
Labels: technical debt, pr-functional-change
